from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(Dialog.minimumSizeHint())
        self.gridLayout_6 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_6.setObjectName("gridLayout_6")

        # Image name row
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setToolTipDuration(10000)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_background = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_background.setObjectName("lineEdit_background")
        self.gridLayout_5.addWidget(self.lineEdit_background, 0, 1, 1, 1)
        self.toolButton_background = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_background.setObjectName("toolButton_background")
        self.gridLayout_5.addWidget(self.toolButton_background, 0, 2, 1, 1)
        self.pushButton_imageFolder = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_imageFolder.setObjectName("pushButton_imageFolder")
        self.gridLayout_5.addWidget(self.pushButton_imageFolder, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 12)

        # Checkboxes + Opacity sliders
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_reviewer = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_reviewer.setToolTipDuration(10000)
        self.checkBox_reviewer.setChecked(True)
        self.checkBox_reviewer.setObjectName("checkBox_reviewer")
        self.gridLayout_4.addWidget(self.checkBox_reviewer, 0, 0, 1, 1)
        self.checkBox_toolbar = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_toolbar.setToolTipDuration(10000)
        self.checkBox_toolbar.setChecked(True)
        self.checkBox_toolbar.setObjectName("checkBox_toolbar")
        self.gridLayout_4.addWidget(self.checkBox_toolbar, 1, 0, 1, 1)
        self.checkBox_topbottom = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_topbottom.setToolTipDuration(10000)
        self.checkBox_topbottom.setChecked(True)
        self.checkBox_topbottom.setObjectName("checkBox_topbottom")
        self.gridLayout_4.addWidget(self.checkBox_topbottom, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 0, 1, 8)

        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.Slider_main = QtWidgets.QSlider(self.groupBox_3)
        self.Slider_main.setMaximum(100)
        self.Slider_main.setPageStep(1)
        self.Slider_main.setProperty("value", 100)
        self.Slider_main.setSliderPosition(100)
        self.Slider_main.setTracking(True)
        self.Slider_main.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Slider_main.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.Slider_main.setTickInterval(5)
        self.Slider_main.setObjectName("Slider_main")
        self.gridLayout_3.addWidget(self.Slider_main, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.Slider_review = QtWidgets.QSlider(self.groupBox_3)
        self.Slider_review.setMaximum(100)
        self.Slider_review.setPageStep(10)
        self.Slider_review.setProperty("value", 1)
        self.Slider_review.setSliderPosition(1)
        self.Slider_review.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Slider_review.setInvertedAppearance(False)
        self.Slider_review.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.Slider_review.setObjectName("Slider_review")
        self.gridLayout_3.addWidget(self.Slider_review, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 1, 8, 1, 4)

        # Attachment / Size / Position / Scale
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox_attachment = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_attachment.setObjectName("comboBox_attachment")
        self.comboBox_attachment.addItem("")
        self.comboBox_attachment.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_attachment, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.comboBox_size = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_size.setObjectName("comboBox_size")
        self.comboBox_size.addItem("")
        self.comboBox_size.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_size, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.comboBox_position = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_position.setObjectName("comboBox_position")
        for item in ["left top", "center top", "right top", "right", "left", "center",
                     "left bottom", "center bottom", "right bottom"]:
            self.comboBox_position.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_position, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 2, 1, 1)
        self.scaleBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.scaleBox.setDecimals(1)
        self.scaleBox.setMinimum(0.1)
        self.scaleBox.setSingleStep(0.1)
        self.scaleBox.setProperty("value", 1.0)
        self.scaleBox.setObjectName("scaleBox")
        self.gridLayout_2.addWidget(self.scaleBox, 1, 3, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 2, 0, 1, 12)

        # Attribution label
        self.label_attribution = QtWidgets.QLabel(Dialog)
        self.label_attribution.setObjectName("label_attribution")
        self.label_attribution.setWordWrap(True)
        self.label_attribution.setOpenExternalLinks(True)
        self.label_attribution.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.gridLayout_6.addWidget(self.label_attribution, 3, 0, 1, 12)

        # Spacer
        spacerItem = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.gridLayout_6.addItem(spacerItem, 4, 0, 1, 1)

        # Buttons row
        self.pushButton_videoTutorial = QtWidgets.QPushButton(Dialog)
        self.pushButton_videoTutorial.setObjectName("pushButton_videoTutorial")
        self.gridLayout_6.addWidget(self.pushButton_videoTutorial, 5, 0, 1, 8)
        self.RestoreButton = QtWidgets.QPushButton(Dialog)
        self.RestoreButton.setObjectName("RestoreButton")
        self.gridLayout_6.addWidget(self.RestoreButton, 5, 8, 1, 3)
        self.OkButton = QtWidgets.QPushButton(Dialog)
        self.OkButton.setObjectName("OkButton")
        self.gridLayout_6.addWidget(self.OkButton, 5, 11, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.adjustSize()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Background Settings"))
        self.label_4.setText(_translate("Dialog", "Attachment:"))
        self.comboBox_attachment.setItemText(0, _translate("Dialog", "fixed"))
        self.comboBox_attachment.setItemText(1, _translate("Dialog", "scroll"))
        self.label_8.setText(_translate("Dialog", "Size:"))
        self.comboBox_size.setItemText(0, _translate("Dialog", "cover"))
        self.comboBox_size.setItemText(1, _translate("Dialog", "contain"))
        self.label_7.setText(_translate("Dialog", "Position:"))
        self.comboBox_position.setCurrentText(_translate("Dialog", "left top"))
        self.comboBox_position.setItemText(0, _translate("Dialog", "left top"))
        self.comboBox_position.setItemText(1, _translate("Dialog", "center top"))
        self.comboBox_position.setItemText(2, _translate("Dialog", "right top"))
        self.comboBox_position.setItemText(3, _translate("Dialog", "right"))
        self.comboBox_position.setItemText(4, _translate("Dialog", "left"))
        self.comboBox_position.setItemText(5, _translate("Dialog", "center"))
        self.comboBox_position.setItemText(6, _translate("Dialog", "left bottom"))
        self.comboBox_position.setItemText(7, _translate("Dialog", "center bottom"))
        self.comboBox_position.setItemText(8, _translate("Dialog", "right bottom"))
        self.label_9.setText(_translate("Dialog", "Scale:"))
        self.RestoreButton.setText(_translate("Dialog", "Restore Default"))
        self.groupBox_3.setTitle(_translate("Dialog", "Background opacity"))
        self.label_5.setText(_translate("Dialog", "Main"))
        self.label_6.setText(_translate("Dialog", "Review"))
        self.label.setToolTip(_translate("Dialog", "<html><head/><body><p>Name of the background image file.</p><p>&quot;Random&quot; will shuffle through defaults</p></body></html>"))
        self.label.setText(_translate("Dialog", "Image name for background:"))
        self.pushButton_imageFolder.setText(_translate("Dialog", "Open Image Folders"))
        self.toolButton_background.setText(_translate("Dialog", "..."))
        self.checkBox_reviewer.setToolTip(_translate("Dialog", "<html><head/><body><p>Show the background image in the reviewer screen</p></body></html>"))
        self.checkBox_reviewer.setText(_translate("Dialog", "Show in reviewer"))
        self.checkBox_toolbar.setToolTip(_translate("Dialog", "<html><head/><body><p>Show the background image in the top and bottom toolbars in addition to the main screen</p></body></html>"))
        self.checkBox_toolbar.setText(_translate("Dialog", "Show in toolbar"))
        self.checkBox_topbottom.setToolTip(_translate("Dialog", "<html><head/><body><p>Set the background position of the toolbars to top and bottom (if the main background position is set to center, this will look cleaner for most images)<br/></p></body></html>"))
        self.checkBox_topbottom.setText(_translate("Dialog", "Toolbar top/bottom"))
        self.label_attribution.setText(
            "The Background dialog feature in the Clazure Design addon is inspired by and developed "
            "based on the addon by AnKing-VIP.<br>"
            "I would like to express my sincere gratitude to the author for sharing such a valuable "
            "solution with the community.<br><br>"
            "Original addon: "
            "<a href=\"https://ankiweb.net/shared/info/1210908941\">"
            "https://ankiweb.net/shared/info/1210908941</a>"
        )
        self.pushButton_videoTutorial.setText(_translate("Dialog", "Video Tutorial"))
        self.OkButton.setText(_translate("Dialog", "OK"))
